QuarkContainer/Quark

- qvisor/src/kvmlib/mod.rs
- qvisor/src/kvmlib/vmspace/uringMgr.rs
Signed-off-by: xiliangMa <xiliangMa@outlook.com>
> fix the uring configuration

- qvisor/src/runc/shim/container.rs
- qvisor/src/runc/shim/container_io.rs
- qvisor/src/runc/shim/process.rs
there is no more exec process in the shim mode, there is no process to forward the tty signal, we have to handle signals ourselves.
> Filter and send signal when copy tty

- qkernel/x86_64-qkernel.json
to support unwind of stack when panic
> add frame pointer for kernel

- qkernel/src/interrupt/mod.rs
- qkernel/src/kernel_def.rs
- qkernel/src/lib.rs
- qkernel/src/syscalls/sys_thread.rs
- qlib/kernel/memmgr/mm.rs
- qlib/kernel/threadmgr/processgroup.rs
- qlib/kernel/threadmgr/session.rs
- qlib/kernel/threadmgr/thread_group.rs
1. fix tlb shootdown not working issues.
2. recycle process groups and sessions when process exit.
> [bugfix] Fix tlbshootdown

- qkernel/src/interrupt/mod.rs
- qkernel/src/lib.rs
- qlib/kernel/memmgr/mm.rs
- qlib/mod.rs
- qlib/task_mgr.rs
- qlib/vcpu_mgr.rs
- qvisor/Cargo.lock
- qvisor/Cargo.toml
- qvisor/src/kernel_def.rs
- qvisor/src/kvm_vcpu.rs
- qvisor/src/main.rs
- qvisor/src/qcall.rs
- qvisor/src/runc/runtime/vm.rs
- qvisor/src/vmspace/mod.rs
1. kick vcpu with immediate_exit
2. kick vcpu concurrently when doing tlbshootdown
> fix tlbshootdown error

- qlib/mutex.rs
to avoid starvation of TryUpgrade when too many TryReads add the lock
value and make lock value never become UPGRADED
> add check of upgraded before TryRead

- qlib/kernel/memmgr/syscalls.rs
> return the current break when failed to create vma

- qvisor/src/runc/container/container.rs
- qvisor/src/runc/runtime/fs.rs
- qvisor/src/runc/shim/service.rs
tested with both docker and container cri
> Cleanup mount after delete shim

- config.json
- qkernel/src/lib.rs
- qlib/config.rs
- qlib/kernel/boot/loader.rs
- qvisor/src/main.rs
- qvisor/src/namespace.rs
- qvisor/src/runc/cmd/command.rs
- qvisor/src/runc/cmd/mod.rs
- qvisor/src/runc/cmd/sandbox.rs
- qvisor/src/runc/container/container.rs
- qvisor/src/runc/container/mod.rs
- qvisor/src/runc/container/mounts.rs
- qvisor/src/runc/runtime/sandbox_process.rs
- qvisor/src/runc/runtime/util.rs
- qvisor/src/runc/sandbox/sandbox.rs
- qvisor/src/runc/shim/container.rs
- qvisor/src/runc/shim/container_io.rs
- qvisor/src/runc/shim/process.rs
- qvisor/src/runc/shim/shim_task.rs
- qvisor/src/runc/specutils/namespace.rs
for kuasar there is no shim process anymore, the boot process will start a task ttrpc server
> Support kuasar sandbox

- qkernel/src/kernel_def.rs
> aarch64: fix compiler error

- qkernel/src/kernel_def.rs
- qkernel/src/lib.rs
- qlib/kernel/asm/aarch64.rs
- qlib/kernel/kernel/timer/timekeeper.rs
- qlib/kernel/threadmgr/task_signals.rs
- qlib/mem/list_allocator.rs
store vcpu local variable into tpidr_el1
> Support vcpu local variable 

- qkernel/src/interrupt/x86_64/mod.rs
- qkernel/src/kernel_def.rs
- qkernel/src/lib.rs
- qlib/kernel/boot/loader.rs
- qlib/kernel/kernel/kernel.rs
- qlib/linux_def.rs
fixing typos.
compilation passed but not tested (my laptop has some dependency issues). But this is very unlikely to break things because the changes are trivial.
> fix typo kernal -> kernel

- qkernel/src/kernel_def.rs
- qkernel/src/lib.rs
- qkernel/src/syscalls/sys_thread.rs
- qkernel/src/syscalls/sys_tls.rs
- qlib/kernel/arch/aarch64/arch_def.rs
- qlib/kernel/arch/aarch64/syscall_entry.s
- qlib/kernel/arch/x86_64/arch_x86.rs
- qlib/kernel/asm/aarch64.rs
- qlib/kernel/memmgr/mm.rs
- qlib/kernel/memmgr/pma.rs
- qlib/kernel/task.rs
- qlib/kernel/taskMgr.rs
- qlib/kernel/threadmgr/task_clone.rs
- qlib/kernel/threadmgr/task_signals.rs
- qlib/kernel/vcpu.rs
- qlib/mem/block_allocator.rs
- qlib/mem/list_allocator.rs
- qlib/task_mgr.rs
- qvisor/src/heap_alloc.rs
- qvisor/src/kvm_vcpu_aarch64.rs
- qvisor/src/runc/runtime/vm.rs
1. fix allocator address issue
2. make Context in Task a arch agnostic struct
3. use ttbr0_el1 as the init sp, no kernel sp used
4. fix pagetable fork issue, add map of mmio address
5. support context swap
> Fix context issue

- cudaproxy/src/cudaproxy.rs
- qkernel/src/syscalls/sys_proxy.rs
- qlib/proxy.rs
- qvisor/src/vmspace/nvidia.rs
- test/vector_add.cu
> finish cudaFree API

- qvisor/src/console/unix_socket.rs
> aarch64: fix slice copy dest length

- qkernel/src/interrupt/aarch64/mod.rs
- qkernel/src/interrupt/aarch64/sysreg.rs
- qkernel/src/kernel_def.rs
- qlib/kernel/asm/aarch64.rs
resolves #1071 . running nginx image will no longer cause exception class 0.
<del>This PR will be rebased when #1038 , #1034  and #1077 get merged. </del> (done)
This PR replaces #1076 .
> aarch64: emulate 'MRS <Xt>, MIDR_EL1' for userspace

- qlib/addr.rs
- qlib/kernel/memmgr/pma.rs
WIP related to #1097.
NOTE: Relevant commit: 4b35919f0e8ea5bbef42f7cf31e5fbe549d7df3c
NOTE: When concluded will be rebased against [armdev-banch](https://github.com/QuarkContainer/Quark/tree/armdev)
NOTE: Current state is _experimental_, can (**and will**) lead to unknown errors if the same type of fault reappears.
> [RFC]Armdev correct missing PTDescriptor Flags for mappings

- README.md
- qkernel/makefile
- qkernel/src/lib.rs
- qkernel/src/syscalls/sys_thread.rs
- qlib/nvproxy/frontend.rs
- qvisor/makefile
- qvisor/src/main.rs
Reverts QuarkContainer/Quark#1174
> Revert "update rust tool chain"

- qkernel/Cargo.toml
- qkernel/src/lib.rs
- qlib/kernel/Kernel.rs
- qlib/kernel/Kernel_cc.rs
- qlib/kernel/fs/host/hostinodeop.rs
- qlib/mem/list_allocator.rs
- qvisor/Cargo.toml
Now cc mode is enabled automatically when cc feature is compiled. The toggle function will be applied after the sev feature is added.
> Fix merge bug

- qkernel/src/interrupt/aarch64/fault.rs
- qkernel/src/lib.rs
- qlib/kernel/arch/aarch64/context.rs
- qlib/kernel/arch/aarch64/mm/pagetable.rs
- qlib/kernel/asm/aarch64.rs
- qlib/kernel/task.rs
- qlib/kernel/threadmgr/task_clone.rs
- qlib/mutex.rs
- qvisor/src/kvm_vcpu_aarch64.rs
- qvisor/src/vmspace/mod.rs
Mostly to make the linter happy.
> aarch64: chore: cleanup

- qkernel/src/interrupt/aarch64/fault.rs
- qkernel/src/interrupt/aarch64/mod.rs
Some commits are not squashed for clarity. This PR will be rebased in the final revision.
> aarch64: refactor PF handler code

- qkernel/src/interrupt/aarch64/fault.rs
Fixes issue #1244.
**Please** test first if you can reproduce #1244, and then apply the commit.
> aarch64: needWrite-flag missing when installing page on PF

- qvisor/Cargo.lock
- qvisor/Cargo.toml
unused dependencies identified by [udeps](https://github.com/est31/cargo-udeps)
> chore: remove unused deps

- qvisor/src/vmspace/nvidia.rs
- qvisor/src/vmspace/xpu/cuda.rs
- qvisor/src/vmspace/xpu/cuda_mem_manager.rs
> CUDA support: support offload and restore cudaFatBinary

- qvisor/src/vmspace/mod.rs
we previously dropped openAt optimization because of symlink bugs. commit 1b4304b4fad615cae04293fb6baffa26e5f1b213 fixes the bug so we can enable the optimization again.
> aarch64: adapt openAt optimization

- qkernel/src/kernel_def.rs
- qkernel/src/lib.rs
- qkernel/src/syscalls/sys_signal.rs
- qlib/kernel/SignalDef.rs
- qserverless/src/qctl/main.rs
- qvisor/src/kvm_vcpu.rs
- qvisor/src/kvm_vcpu_x86.rs
- qvisor/src/main.rs
- qvisor/src/runc/runtime/sandbox_process.rs
> chore: typos and clean ups

- qlib/kernel/Kernel.rs
- qlib/kernel/fs/procfs/inode.rs
- qlib/kernel/fs/sys/devices.rs
- qlib/qmsg/qcall.rs
- qvisor/src/qcall.rs
- qvisor/src/runc/runtime/sandbox_process.rs
- qvisor/src/vmspace/mod.rs
After implement /sys/devices/system/cpu, the mpirun still doesn't work.
> implement /sys/devices/system/cpu

- qvisor/src/kvm_vcpu.rs
- qvisor/src/kvm_vcpu_x86.rs
- qvisor/src/runc/runtime/vm.rs
enable single iothread, disable vcpu random, this is workaround for GPUVirt, won't be committed in main branch
> enable single iothread,  won't be commited in main branch 

- qkernel/src/syscalls/sys_utsname.rs
- qlib/kernel/version.rs
> aarch64: adjust SysUname - return correct machine type

- qlib/kernel/arch/aarch64/syscall_entry.s
> aarch64: context_swap - adjust 3rd & 4rth parameter

- qlib/mod.rs
- qvisor/src/kvm_vcpu_aarch64.rs
- qvisor/src/kvm_vcpu_x86.rs
> hypercalls: remove obsolete HYPERCALL_U64

- qkernel/src/syscalls/sys_shm.rs
- qkernel/src/syscalls/syscalls.rs
> fix shmdt and inotify_init syscalls
