QuarkContainer/Quark

qkernel/src/socket/control.rs
qkernel/src/socket/unix/unix.rs

Test case is UnboundDgramUnixSocketPairTest.SendtoWithoutConnectPassCreds

Fix Unix Socket pass credential handling when sender doesn't provide crendentials

---

qkernel/src/socket/hostinet/socket.rs

This is a no-op and should be ignored when calling recvmsg(fd, msg, MSG_CTRUNC), rather than return PosixError 22: Invalid argument

add MSG_CTRUNC flag for hostinet

---

.gitignore
qkernel/Cargo.lock
qkernel/Cargo.toml
qkernel/src/lib.rs
qvisor/Cargo.lock
qvisor/Cargo.toml
qvisor/src/main.rs

There're 2 issues with latest rustc and rdma check in:
1. asm is not global any ore which failed to compile x86_64 with version 0.14.3.
2. path of rdma-sys was hardcoded, change it to relative path
3. remote asm feature attribute to remove warning as from rustc 1.59, asm is not a feature any mroe

Make Quark compile with latest rustc and rdma check in

---

qvisor/Cargo.lock
qvisor/Cargo.toml

as the lib is removed from crates.io. see https://crates.io/crates/capabilities/0.3.0

update dependency capabilities to be from git repo ..

---

qlib/cpuid.rs
qlib/kernel/fs/procfs/stat.rs
qlib/kernel/fs/procfs/task/mounts.rs

1. no new line between each core in cpuinfo file
2. show all cpu cores in /proc/stat(although no real cpu stats displayed
yet)
3. lack of a space between mount path and access right in mountinfo

fix procfs file bugs

---

qkernel/src/interrupt/mod.rs
qkernel/src/lib.rs
qvisor/Cargo.lock
qvisor/Cargo.toml
qvisor/src/kernel_def.rs
qvisor/src/kvm_vcpu.rs

remove the waiting of vcpu interrupt, as we assume that kvm will interrupt the vcpu in a timely manner。

fix tlbshootdown deadlock

---

qlib/kernel/kernel/waiter/entry.rs
qlib/kernel/kernel/waiter/queue.rs

Discovered when run apache-benchmark, verified with both apache-benchmark and redis benchmark.

Clear bitmap when unregister event

---

qvisor/src/runc/container/container.rs
qvisor/src/runc/runtime/sandbox_process.rs

The "clean up" is done when "quark_d delete" is triggered.

clean up mounts and directories inside /var/lib/quark/ after container being removed

---

qvisor/src/runc/container/container.rs
qvisor/src/runc/runtime/fs.rs
qvisor/src/runc/shim/service.rs

also let sandbox shim delete wait for 100 ms to avoid race condition, these logic should be revisited when kuasar is enabled

Retry umount container fs when got device busy.

---

doc/k8s_setup.md

starting with 1.20 the command  for allowing scheduling of pods on Kubernetes master should be: kubectl taint node mymasternode  node-role.kubernetes.io/control-plane:NoSchedule-

Starting with 1.20 the kubectl taint is changed

---

qvisor/src/runc/sandbox/sandbox.rs
qvisor/src/runc/shim/container.rs
qvisor/src/runc/shim/container_io.rs
qvisor/src/runc/shim/process.rs
qvisor/src/runc/shim/shim_task.rs

Now, the `control c` sent over the console from the client can be forwarded to qkernel properly.
On top of that, we stop the io redirection thread in shim right after qkernel exec process exit so that terminal on the client side can exit properly.
Tiny issue: we got an error message "error stream protocol error: invalid exit code value "33280" after we terminate the console.
```yaoxin@yaoxin-MS-7B48:/var/log/quark$ kubectl exec -it nginx-quark /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: error stream protocol error: invalid exit code value "33280"
```

Fix bug: terminal signal filtering, and allow remote terminal termination

---

config.json
qkernel/Cargo.lock
qkernel/Cargo.toml
qkernel/src/lib.rs
qkernel/src/print.rs

The log crate provides a single logging API that abstracts over the actual logging implementation. Libraries use the logging API provided by this crate, and the consumer of those libraries (qkernel) uses the logging implementation `SimpleLogger` to capture and print the logs to `quark.log`

Log enhancement: enable qkernel capture log message from Libraries 

---

qkernel/src/lib.rs

`HEAP_START` and `HEAP_SIZE` are defined in `linux_def::MemoryDef::`.  Definitions in `qkernel/lib.rs` are unused and would cause confusions.

remove dead code

---

qkernel/src/syscalls/sys_thread.rs
qkernel/src/syscalls/sys_tls.rs
qlib/kernel/arch/aarch64/arch_def.rs
qlib/kernel/arch/aarch64/context.rs
qlib/kernel/arch/aarch64/mod.rs
qlib/kernel/arch/mod.rs
qlib/kernel/arch/x86_64/arch_x86.rs
qlib/kernel/arch/x86_64/context.rs
qlib/kernel/arch/x86_64/mod.rs
qlib/kernel/loader/elf.rs
qlib/kernel/memmgr/arch.rs
qlib/kernel/memmgr/mm.rs
qlib/kernel/mod.rs
qlib/kernel/task.rs
qlib/kernel/taskMgr.rs
qlib/kernel/threadmgr/task_clone.rs
qlib/kernel/threadmgr/task_signals.rs
qlib/pagetable.rs
qlib/task_mgr.rs

This commit identifies, and excludes x86_64 code "qlib/kernel/arch/x86_64/*" which was still included when build for aarch64. This seems to be mostly code related to context save/switch.
AFAIK context save/switch for aarch64 is still not present, so ensure that the branch still builds, dummy structs/functions are placed in "qlib/kernel/arch/aarch64/*".

Armdev - exclude specific x86_64 code 

---

qlib/addr.rs
qlib/kernel/arch/aarch64/mm/pagetable.rs
qlib/linux_def.rs
qvisor/src/kvm_vcpu_aarch64.rs
qvisor/src/runc/runtime/vm.rs

- HYPERCALL_MMIO_BASE is relocated to 2 pages below PHY_LOW_ADDR  (256G - 8K)
- It turns out that with MMU we don't need to align (mmio) hypercall addresses to 8 bytes.
test run from our arm machine (Neoverse-N1). I annotated the hypercalls. 
```
tack is 45c0080000
[INFO] [0/225894469457] enter vcpu run
[INFO] [0/225894469459] kvmRet: MmioWrite(274877898760, [0, 0, 0, 0])
[INFO] [0/225894469459] handle hypercall 274877898760    <- HYPERCALL_PRINT
[INFO] [0/225894469459] paras:45c007fdd0 0 0 0
0x40003d622f 0x45c007fde0: enter rust_main, haha         <- rust_main
[INFO] [0/225894469459] enter vcpu run
[INFO] [0/225894469460] kvmRet: MmioWrite(274877898760, [0, 0, 0, 0])
[INFO] [0/225894469460] handle hypercall 274877898760    <- HYPERCALL_PRINT
[INFO] [0/225894469460] paras:45c007fc68 0 0 0 …
```

[aarch64] fix page table flags; add identity mapping of device MMIO

---

qlib/kernel/asm/aarch64.rs
qlib/kernel/asm/x86_64.rs
qlib/kernel/task.rs

NOTE: we can only get sp_el1 in EL2 and EL3, so we have to get sp_el1 by mov and set the SPSel

aarch64: rename GetRsp to GetCurrentKernelSp and implement it in aarch64

---

qvisor/src/kvm_vcpu_aarch64.rs
qvisor/src/runc/runtime/vm.rs

In "qvisor/(SOME_LONG_PATH)/runtime/vm.rs", the _MAP_FIXED_ flag in ```mmap(addr, ..., MAP_FIXED ...)``` causes _mmap_ to take the _addr_ parameter as fact, which in this call is ```std::ptr::null_mut()```, leading in undesired behavior. The mapping is not related to an opened file, _fd = -1_.
Late addition, fixed initialization of CPACR_EL1 register, related to FP-functionality.

Armdev - Removed non-compatible flag from mmap(...) in QVisor 

---

README.md

- Identified an issue where using 'sudo systemctl restart docker' does not always forcibly restart the 'docker.service'.
- Implemented a check to ensure that 'sudo systemctl restart docker.service' is explicitly called for a consistent restart behavior.
- This fix aims to address the inconsistent behavior observed in some cases when restarting Docker using systemctl commands.

Fix for Docker start behavior with systemctl

---

qkernel/src/interrupt/aarch64/mod.rs
qkernel/src/lib.rs
qlib/kernel/arch/aarch64/exception.s
qlib/kernel/arch/aarch64/syscall_entry.s
qlib/kernel/vcpu.rs

This PR adds the exception vector table and syscall handler.
I haven't tested this implementation (at least code compiles and runs) because we can't go to userspace yet, and only the el0->el1 exceptions are handled.
**Revision(s)**
- v1 > v2 : fixed typo, remove unnecessary `mut`
- v2 > v3: rebase against armdev with #1011  ; pass NULL as call frame pointer upon empty entry.
- v3 > v4: refined register save/restore for el0 and el1 exceptions; include sp_{el0,el1} into the frame. Renamed ExceptionStateEl1 to ExceptionFrame.
Major update (v4 > v5) :
- unified exception frame and PtRegs definitions.
- added diagnostics for data/instr aborts.
- added exception handlers for el1h_sync
small fix: fixed DFSC_ names (should be _Ln instead of _ELn)
Also please note that since we use PtRegs now …

[RFC] Add exception table and syscall handler

---

qvisor/src/ucall/usocket.rs

the length of source and destination slice should be equal otherwise it will panic to call `copy_from_slice`

aarch64: fix slice copy issue

---

qkernel/src/syscalls/sys_stat.rs
qlib/kernel/fs/host/util.rs
qlib/linux_def.rs

The struct definition of `stat` is slightly different in x86 and aarch64

aarch64：distinguish between x86 and aarch64 for the definition of LibcStat

---

qlib/kernel/arch/aarch64/exception.s

Sorry folks I had a stupid mistake in previous commit where I forgot to actually call the routine to save/restore the registers in the PtRegs format. This PR fixes it.
as of now, with this fix, the #1034 encounters PF exceptions endlessly @chl337 
I'm merging this without review because the change is trivial, however please be noticed of the change because the program would behave differently. @CharlyYu

aarch64: fix: save/restore regs in ptregs format

---

qkernel/src/interrupt/aarch64/mod.rs
qkernel/src/lib.rs

quick bug fix: the exception handler (sync_el0) should set the task state to kernel.

aarch64: account task leave in exception handler

---

qkernel/src/syscalls/syscalls.rs

simply return ENOSYS to notify userspace sys_rseq is disabled / not supported. See #1078 for details.

aarch64: add psuedo sysrseq

---

qlib/addr.rs
qlib/kernel/arch/aarch64/mm/pagetable.rs
qlib/kernel/memmgr/pma.rs
qlib/linux_def.rs
qvisor/src/runc/runtime/vm.rs

1. no longer map MMIO mem regions in the host side
2. clean up the definition of PageTableFlags, improve bitops syntax
3. ~more verbose debug info during PF~
4. ~add function to dump all valid pagetables~
**Note on merge yet** : will be rebased after #1034

armdev: cleanup page mapping

---

qkernel/src/kernel_def.rs
qlib/kernel/asm/aarch64.rs

by setting and unsetting PAN (when feature supported). To enable cpu feature, add "+pan" in the features (aarch64-qkernel.json). Otherwise the enable_access_user() and set_access_user() simply return.

aarch64: control accessing user mem from EL1

---

qkernel/src/interrupt/aarch64/mod.rs
qlib/kernel/task.rs

Save tpidr_el0 to task.context.tls when leaving EL0.
Fixes #1091

aarch64: save tls when leaving el0

---

qkernel/src/lib.rs
qkernel/src/syscalls/sys_tls.rs
qlib/kernel/asm/aarch64.rs
qlib/kernel/vcpu.rs

Also:
- guard unimplemented with todo!() macro
- remove SysArchPrctl for aarch64

aarch64: remove x86 specific code

---

qkernel/src/interrupt/aarch64/mod.rs

In case some legal _mrs_-instruction did not cause the exception, log the PC and, if possible, the opcode before panic.

aarch64: add debug context for UnknownException in EL0

---

qkernel/src/interrupt/aarch64/mod.rs
qlib/kernel/memmgr/mm.rs

In aarch64, we use an extra page below the _KVM_IOEVENTFD_BASEADDR_ page for Hypercalls, _HYPERCALL_MMIO_BASE_. Till now, we have missed including it in the memory management bookkeeping.

aarch64: include HYPERCALL_MMIO in Kernel memory-space.

---

qkernel/src/interrupt/aarch64/fault.rs
qlib/kernel/threadmgr/task_clone.rs

~Handel Write-PF on COW-cloned VMA.~
Continuous on top of #1106
CURRENT_STATUS:
- No panic on Write-PF while from the parent.
- ~Translation fault on child => FAR == 0x0.~
- Enter cloned task front-end.
- Panic on non-implemented function.
TODO: Replace _SyscallRet()_, which is not a concept on aarch64, with _IRet()_.
REPRODUCE:
- [Test](https://github.com/QuarkContainer/Quark/pull/1131#issuecomment-1983456663)
- Non-merged commits: d002ccd9703ee744774f3405a4bade945c07e24a 560220a3df403827e2b3f40da933fe3ee10252c8 e6566305a01ee79347f3cdcfc9ede21795cce822 e6566305a01ee79347f3cdcfc9ede21795cce822
Issue: #1099, #1146
NOTE: I think there should be an improvement on how COW areas are bookkept, and a SW-defined bit in the PTE should be used to mark them as COW-shared.

aarch: handel Task Clone

---

qkernel/src/interrupt/aarch64/mod.rs
qkernel/src/syscalls/syscalls.rs
qlib/mod.rs

Related to #1161
+ 550dbd88c4bef21e444482dc7639db4e16691bee makes the syscall-number validity [check](https://github.com/QuarkContainer/Quark/blob/bf8725fde4ba3e2271a8ca83da0475f3ecdb2658/qkernel/src/lib.rs#L382) consistent.
+ 61336b29328fa14ee2e8b672482fffd1349ee93b produces helpful log information.
+ c122ccb38060d3f03b20332234b03c2e90460cf4 aqv. of linux sys_ni_syscall.
Regarding #1161, it avoids hitting the breakpoint instruction; we should not get there. In the general case, it will log if a non-implemented syscall was called.

Armdev syscall id table consistent

---

README.md
makefile
qvisor/Cargo.lock
qvisor/Cargo.toml
qvisor/makefile
qvisor/src/vmspace/mod.rs
qvisor/src/vmspace/xpu/mod.rs

After this commit, by default make won't build cuda, so there is no cuda dependency by default. In machine with cuda library, need to do make cuda_all, (or cuda_debug, cuda_release etc) to build cuda.

Separate cuda build from non cuda machine

---

qlib/addr.rs

sys_mprotect will reset the page flag, but currently the UserNonAccessable/UserReadOnly/UserReadWrite definition is missing the MT_NORMAL, this will cause a pagefault of the installed page, and we will install another page.

aarch64: fix mprotect syscall

---

qlib/kernel/loader/loader.rs

otherwise libc may call some instructions based on the hwcap and make a UNKNOWN_EXCAPTTION

aarch64: do not set a x86_64 hwcap to auxv

---

qkernel/src/syscalls/syscalls.rs

For aarch64, only the gentdents64 syscall, and by extension, the linux_dirent64 is valid. Using the old gentdents API breaks userspace.
fixes #1195
Simple one-liner fix, but tedious debugging. orz

aarch64: fix getdents64 syscall.

---

README.md

The current readme is barely readable in its source.  (try cat it!)
This patch fixes line width to 80 chars, also fixes a few typos.

proper line wrap in README.md

---

qlib/kernel/arch/aarch64/exception.s
qlib/kernel/asm/aarch64.rs
qlib/pagetable.rs
qvisor/src/kvm_vcpu_aarch64.rs

@CharlyYu may I have your Signoffs  for the first two commits? since you suggested the changes. You could also push them on your own if you prefer.
(I added `Suggested-by` commit trailers, but are not recognized by github)
This fixes the fork-wait issues we had.
1. restore userspace sp correctly
2. invalidate tlb when switching address space
3. <del> (wip) ignore some panic conditions in PF handler </del>
[The test programs](https://github.com/QuarkContainer/Quark/issues/1210#issuecomment-2091829056) work without issue.
Note: for the above testing program to work, take #1215 as well.

aarch64: fix context switching issues

---

qkernel/src/interrupt/aarch64/fault.rs
qkernel/src/syscalls/sys_mmap.rs
qlib/kernel/arch/aarch64/mm/pagetable.rs
qlib/kernel/loader/elf.rs
qlib/kernel/memmgr/syscalls.rs
qlib/pagetable.rs

breaking change: `MemoryManager::MProtect` function now receives another parameter `permOnly`. When passed true, the MProtect routine will NOT touch PTE flags other than permission related ones. This prevents `mprotect` from corrupting PTEs, which causes weird page faults.  Related: #1131
Ideally the `MProtect` function should NEVER touch PTE flags such as `PRESENT` or `TABLE`. This is wrong semantics. However both x86 and aarch64 code relies this to set up forked address spaces, or load new ELFs. We could do some refactoring in the future. 
On PF handling: as suggested by @QuarkContainer , we skip page swapping for now.

aarch64: refactor paging and page fault handler

---

qkernel/src/interrupt/aarch64/mod.rs
qkernel/src/syscalls/sys_signal.rs
qlib/kernel/SignalDef.rs
qlib/kernel/arch/aarch64/arch_def.rs
qlib/kernel/loader/loader.rs
qlib/kernel/memmgr/mm.rs
qlib/kernel/memmgr/pma.rs
qlib/kernel/taskMgr.rs
qlib/kernel/threadmgr/task_signals.rs

**[updated!]** There are some todos, see commit messages. Anyways for the scope of this PR I'll stop here.
we have the basic stuffs running without issues now. try container `ubuntu bash`

aarch64: implement signal delivery

---

qlib/kernel/memmgr/mm.rs

It will cause failure when tracking read-only pages and then writing back before unmapping.

[cc_quark]Track shared page only when writeable

---

qkernel/src/print.rs
qlib/kernel/SignalDef.rs

* Pretty format for _struct PtRegs_
* Update outdated comment
* Distinguish output log from the kernel
* ~remove dead code~

aarch64: improved log format and clean ups

---

qlib/kernel/kernel_util.rs

```
this is devil hidding in plain sight
pub fn RandU128() -> Result<(u64, u64)> {
let res: [u64; 2] = [0; 2];
Random(&res[0] as *const _ as u64, 18, GRND_RANDOM)?;
^^^^
this is off by 2,
should be 16.
return Ok((res[0], res[1]));
}
causing a stack overrun. The behaviour is kinda random and never spotted on x86.
```

fix random gen

---

qkernel/src/syscalls/sys_epoll.rs
qkernel/src/syscalls/sys_poll.rs
qlib/kernel/guestfdnotifier.rs
qlib/kernel/kernel/epoll/epoll.rs
qlib/kernel/kernel/epoll/epoll_entry.rs
qlib/kernel/quring/uring_async.rs
qlib/linux_def.rs
qvisor/src/vmspace/hostfdnotifier.rs

the userData is sometimes defined as [i32; 2] in Quark code. This doesn't make sense to me because the data is used in one piece as a u64 anyways. But I may be wrong.
However I don't see where this array is converted into u64, am I missing something? What's the initial idea of define the userData as [i32; 2] ?
This is tested on both x86 and aarch64, I don't see regression so far. Also fixes #1230 
CC @QuarkContainer

epoll: define EpollEvent structure per linux API

---

qlib/kernel/kernel/epoll/epoll.rs
qlib/linux_def.rs

otherwise it may cause alignment issue
Suggested-by: Yiliang Dong  <dongyiliangsteven@163.com>

epoll: use repr(packed) for EpollEvent

---

qkernel/.cargo/config.toml
qkernel/makefile

we need to build the toolchain because qkernel (arch-qkernel.json) is not one of the default targets. We have been using the cargo-xbuild tool for this and it worked fine, however it's not  under active maintance for ~ 2 years and there could be some issues with newer rust toolchain as of May, 2024.
Rust's build-std is a unstable feature that does the same thing: we tell it to build the components e.g. core, alloc, builtins ... in the .cargo/config.toml so that cargo builds them with the custom target specified by `--target xyz.json`. To use this, simply replace the `cargo xbuild` with `cargo build` in qkernel's makefile, nothing else needs to change. (this approach is also noted in cargo-xbuild's docs)
Since cargo xbuild is not breaking (yet) and the build-std is not a unstable feature …

toolchain: enable using cargo's own build-std

---

qlib/kernel/SignalDef.rs
qlib/kernel/loader/vdso.rs
qlib/kernel/threadmgr/task_signals.rs

**TODO**:
* ~replace hard-coded _vdso_-symbol value with query~
* ~refactor~
* ~rebase~
* ~test on x86 machine for sanity~

aarch64: vdso symbols

---

qlib/kernel/SignalDef.rs

should fix #1330
supersedes #1331 (the second commit is technically doing the same as 1331, but 1331 was a wrong take. The sigset should be padded to 128 bytes (i.e. adding 120 bytes padding), the problem is that the sigcontext should be padded to 16 bytes.
There is also a alignment bug in the signalstack
test wanted.
@chl337 @mhomidi

Fix paddings in signal structs

---

doc/perf_test.md

I think 'Performance Test Result and Comparison' should be a title and it may well be the doc writer's true intention.

'Performance Test Result and Comparison' as a title

---

qvisor/src/vmspace/mod.rs

For the first level entry, the USER_ACCESSIBLE flag should be set.

fix: page table initialization flags
